### ISSUE TITLE
“SameSite” attribute set to “None”

### ISSUE THREAD

**Issue by arhimede** [dotkernel/dot-session#10]
Message in Console:

Cookie “COMPANY_SESSID” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

we need to investigate this

**Comment by arhimede** [comment]
Let's wait until laminas_session solve the issue on their side. 
Upstream 

https://github.com/laminas/laminas-session/pull/30

**Comment by alexmerlin** [comment]
Closing this issue as it is no longer relevant.

**Reason**:
The SameSite-related cookie issues have been fixed in the meantime in both [admin](https://github.com/dotkernel/admin/blob/4.0/config/autoload/session.global.php#L61) and [frontend](https://github.com/dotkernel/frontend/blob/4.0/config/autoload/session.global.php#L61).
